### ISSUE TITLE
yii\base\ErrorException: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-embedded-assets#131]
#### Description

I can't add my TikTok URL (`https://www.tiktok.com/@lexnotalexis/video/6821608032351374597`).

Each time, I got the following error:
```
[-][1][ovnq9j13jm20m8eqoe21e6ilc6][error][yii\base\ErrorException:8] yii\base\ErrorException: A non well formed numeric value encountered in /vendor/spicyweb/craft-embedded-assets/src/Service.php:215
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'A non well form...', '/export/hosting...', 215)
#1 /vendor/spicyweb/craft-embedded-assets/src/Service.php(215): craft\web\ErrorHandler->handleError(8, 'A non well form...', '/export/hosting...', 215, Array)
#2 /vendor/spicyweb/craft-embedded-assets/src/Service.php(54): spicyweb\embeddedassets\Service->createEmbeddedAsset(Array)
#3 /vendor/spicyweb/craft-embedded-assets/src/Controller.php(199): spicyweb\embeddedassets\Service->requestUrl('https://www.tik...')
#4 [internal function]: spicyweb\embeddedassets\Controller->actionPreview()
#5 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('preview', Array)
#8 /vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('preview', Array)
#9 /vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('embeddedassets/...', Array)
#10 /vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('embeddedassets/...', Array)
#11 /vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /htdocs/index.php(21): yii\base\Application->run()
#14 {main}
2020-05-18 13:40:23 [-][1][ovnq9j13jm20m8eqoe21e6ilc6][info][application] $_GET = [
    'p' => 'admin/actions/embeddedassets/actions/preview'
    'showContent' => '1'
    'callback' => 'embeddedassets5bo94b99yr86'
    'url' => 'https://www.tiktok.com/@lexnotalexis/video/6821608032351374597'
]
```

#### Steps to reproduce
1. Try to add a new embed using `https://www.tiktok.com/@lexnotalexis/video/6821608032351374597` URL 
2. Check the logs

#### Other information
- Embedded Assets version: 2.2.3
- Craft CMS version: Craft Pro 3.4.19.1

**Comment by ttempleton** [comment]
Hi @romainpoirier,

Support for TikTok is included in a newer version of the [oscarotero/Embed](https://github.com/oscarotero/Embed) library than Embedded Assets currently uses.  I will aim to update the library, test and release a new version of Embedded Assets in the next few days.

**Comment by ttempleton** [comment]
It turns out that this error, while specific to TikTok as far as I can tell, was unrelated to the embed library version requirement update that added full support for TikTok.  In any case, Embedded Assets 2.2.4 should now have full TikTok compatibility.  Thanks for reporting, @romainpoirier!
