### ISSUE TITLE
TypeError: Return value of spicyweb\embeddedassets\Service::requestUrl() must be an instance of spicyweb\embeddedassets\models\EmbeddedAsset

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-embedded-assets#132]
#### Description

I can't add my Giphy URLs (`https://media.giphy.com/media/Z6m2HqMOpSaxW/giphy.gif` or `https://giphy.com/gifs/Z6m2HqMOpSaxW/html5`).

Each time, I got the following error:
```
[-][1][ovnq9j13jm20m8eqoe21e6ilc6][error][TypeError] TypeError: Return value of spicyweb\embeddedassets\Service::requestUrl() must be an instance of spicyweb\embeddedassets\models\EmbeddedAsset, null returned in /vendor/spicyweb/craft-embedded-assets/src/Service.php:59
Stack trace:
#0 /vendor/spicyweb/craft-embedded-assets/src/Controller.php(199): spicyweb\embeddedassets\Service->requestUrl('https://media.g...')
#1 [internal function]: spicyweb\embeddedassets\Controller->actionPreview()
#2 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('preview', Array)
#5 /vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('preview', Array)
#6 /vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('embeddedassets/...', Array)
#7 /vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('embeddedassets/...', Array)
#8 /vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /htdocs/index.php(21): yii\base\Application->run()
#11 {main}
2020-05-18 13:38:48 [-][1][ovnq9j13jm20m8eqoe21e6ilc6][info][application] $_GET = [
    'p' => 'admin/actions/embeddedassets/actions/preview'
    'showContent' => '1'
    'callback' => 'embeddedassets6y5y90e4up27'
    'url' => 'https://media.giphy.com/media/Z6m2HqMOpSaxW/giphy.gif'
]
```

#### Steps to reproduce
1. Try to add a new embed using `https://media.giphy.com/media/Z6m2HqMOpSaxW/giphy.gif` or `https://giphy.com/gifs/Z6m2HqMOpSaxW/html5` URL 
2. Check the logs

#### Other information
- Embedded Assets version: 2.2.3
- Craft CMS version: Craft Pro 3.4.19.1

**Comment by ttempleton** [comment]
Thanks for reporting this, @romainpoirier, this has been fixed in Embedded Assets 2.2.4.
