### ISSUE TITLE
TikTok URLs can't be added

### ISSUE THREAD

**Issue by Samangie** [spicywebau/craft-embedded-assets#225]
### Bug Description

TikTok URLs can't be added. I tried different URLs but none of them worked. 

I receive the following error: 
```
2023-03-14 15:40:37 [web.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: A non-numeric value encountered in C:\xampp\htdocs\base\craft\vendor\spicyweb\craft-embedded-assets\src\Service.php:286
Stack trace:
#0 C:\xampp\htdocs\base\craft\vendor\craftcms\cms\src\web\ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'A non-numeric v...', 'C:\\xampp\\htdoc...', 286)
#1 C:\xampp\htdocs\base\craft\vendor\spicyweb\craft-embedded-assets\src\Service.php(286): craft\web\ErrorHandler->handleError(2, 'A non-numeric v...', 'C:\\xampp\\htdoc...', 286)
#2 C:\xampp\htdocs\base\craft\vendor\spicyweb\craft-embedded-assets\src\Service.php(70): spicyweb\embeddedassets\Service->createEmbeddedAsset(Array)
#3 C:\xampp\htdocs\base\craft\vendor\spicyweb\craft-embedded-assets\src\Controller.php(183): spicyweb\embeddedassets\Service->requestUrl('https://www.tik...')
#4 [internal function]: spicyweb\embeddedassets\Controller->actionPreview()
#5 C:\xampp\htdocs\base\craft\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\base\craft\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\base\craft\vendor\yiisoft\yii2\base\Module.php(552): yii\base\Controller->runAction('preview', Array)
#8 C:\xampp\htdocs\base\craft\vendor\craftcms\cms\src\web\Application.php(302): yii\base\Module->runAction('embeddedassets/...', Array)
#9 C:\xampp\htdocs\base\craft\vendor\craftcms\cms\src\web\Application.php(627): craft\web\Application->runAction('embeddedassets/...', Array)
#10 C:\xampp\htdocs\base\craft\vendor\craftcms\cms\src\web\Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 C:\xampp\htdocs\base\craft\vendor\yiisoft\yii2\base\Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 C:\xampp\htdocs\base\craft\web\index.php(12): yii\base\Application->run()
#13 {main} {"memory":19437704,"exception":"[object] (yii\\base\\ErrorException(code: 2): A non-numeric value encountered at C:\\xampp\\htdocs\\base\\craft\\vendor\\spicyweb\\craft-embedded-assets\\src\\Service.php:286)"} 
2023-03-14 15:40:37 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'admin/actions/embeddedassets/actions/preview'
    'showContent' => '1'
    'callback' => 'embeddedassets0im7d7yxgp4511'
    'url' => 'https://www.tiktok.com/@vivage.ch/video/7194478354903485701'
]
```

I found this ticket with the same error. Maybe the problem is similar? https://github.com/spicywebau/craft-embedded-assets/issues/131

### Steps to reproduce

1. Try to add a new embed using https://www.tiktok.com/@vivage.ch/video/7194478354903485701
2. Check logs

### Embedded Assets version

3.1.1

### Craft CMS version

4.4.1

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 3.1.2.
