### ISSUE TITLE
Error embedding Instagram: max 10 redirects followed 

### ISSUE THREAD

**Issue by arifje** [spicywebau/craft-embedded-assets#233]
### Bug Description

Since a few days we're unable to embed instagram posts. Getting the following error when pasting an URL;

```
{
	"trace": ["#0 /var/www/xxx/cms/vendor/embed/embed/src/Embed.php(81): Embed\\Embed::process()", "#1 /var/www/xxx/cms/vendor/spicyweb/craft-embedded-assets/src/Service.php(135): Embed\\Embed::create()", "#2 /var/www/xxx/cms/vendor/spicyweb/craft-embedded-assets/src/Service.php(69): spicyweb\\embeddedassets\\Service->_getDataFromAdapter()", "#3 /var/www/xxx/cms/vendor/spicyweb/craft-embedded-assets/src/Controller.php(207): spicyweb\\embeddedassets\\Service->requestUrl()", "#4 [internal function]: spicyweb\\embeddedassets\\Controller->actionPreview()", "#5 /var/www/xxx/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()", "#6 /var/www/xxx/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()", "#7 /var/www/xxx/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()", "#8 /var/www/xxx/cms/vendor/craftcms/cms/src/web/Application.php(302): yii\\base\\Module->runAction()", "#9 /var/www/xxx/cms/vendor/craftcms/cms/src/web/Application.php(627): craft\\web\\Application->runAction()", "#10 /var/www/xxx/cms/vendor/craftcms/cms/src/web/Application.php(281): craft\\web\\Application->_processActionRequest()", "#11 /var/www/xxx/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest()", "#12 /var/www/xxx/cms/web/index.php(29): yii\\base\\Application->run()", "#13 {main}"],
	"memory": 13904008,
	"exception": "[object] (Embed\\Exceptions\\InvalidUrlException(code: 0): Maximum (10) redirects followed at /var/www/xxx/cms/vendor/embed/embed/src/Embed.php:144)"
}
```

### Steps to reproduce

![Screenshot 2023-05-15 at 12 30 42](https://github.com/spicywebau/craft-embedded-assets/assets/1286410/988499ff-6ebf-4b1c-911e-c7f145a554af)

### Expected behaviour

Show the preview

### Embedded Assets version

3.1.5

### Craft CMS version

Craft Pro 4.4.9

**Comment by ttempleton** [comment]
This is likely caused by https://github.com/oscarotero/Embed/issues/516. Will keep an eye on that issue.
